### ISSUE TITLE
Mac端隐藏Dock栏图标

### ISSUE THREAD

**Issue by Orange-Lee** [ghotst0xdeadbeef/Greenhub-desktop#11]
建议Mac客户端可选择隐藏Dock栏图标，这样可以只保留菜单栏图标，随时可启用，并且保持Dock栏的清爽

**Comment by ghotst0xdeadbeef** [comment]
https://github.com/ghotst0xdeadbeef/Greenhub-desktop/releases/tag/1.0.2

1.0.2版本已经增加
