### ISSUE TITLE
桌面端似乎崩了

### ISSUE THREAD

**Issue by Ender-003** [ghotst0xdeadbeef/Greenhub-desktop#2]
如图

[![oQQ7lj.png](https://z3.ax1x.com/2021/11/29/oQQ7lj.png)](https://imgtu.com/i/oQQ7lj)

**Comment by ghotst0xdeadbeef** [comment]
你好，请更新到最新版本试一下，如果还有问题，是否可以提供一下电脑平台（win或者mac），网络dns等截图，以便定位你遇到的问题

**Comment by ghotst0xdeadbeef** [comment]
网络波动，目前已恢复
