### ISSUE TITLE
github挂个名，假开源罢了。还搞起收费，难以信任。趁早散了把

### ISSUE THREAD

**Issue by ZARD20** [ghotst0xdeadbeef/Greenhub-desktop#39]
github挂个名，假开源罢了。还搞起收费，难以信任。趁早散了把

_Originally posted by @Syouei in https://github.com/ghotst0xdeadbeef/Greenhub-desktop/issues/33#issuecomment-1189716388_更新完，发现收费就卸载了，还看了一下收费，12个月要35.9（不知道是美元还是人民币）

**Comment by huoyu220** [comment]
都一样，无奈
